version: '3.8'
services:
  db:
    container_name: pg_container_slightli
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: slightli-cloudi_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container_slightli
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"